const express=require('express')
const app=express()
app.use(express.json())
const bodyParser=require('body-parser')
const cors=require('cors')   // browser mechanism which enables controlled access to resources located outside of a given domain
const path = require('path');
app.use(bodyParser.urlencoded({extended:false}))
app.use(cors())
const db=require('./database/db')
const user_route=require('./route/userRoute')
const ailaRoute=require('./route/hotelRoute')
const cartRoute=require('./route/cartRoute')
const favoriteRoute=require('./route/favoriteRoute')
const contactRoute=require('./route/contactRoute')
app.use('/images', express.static(path.join(__dirname, '/images')))
app.use(user_route)
app.use(ailaRoute)
app.use(cartRoute)
app.use(favoriteRoute)
// const publicDir=path.join(__dirname,'images')
// app.use(express.static(publicDir))
app.use(contactRoute)
app.use(express.static('images'))
app.listen(90,()=>{
    console.log("App running on port:90")
})